USE [FILE_SHARING_DB]

GO

DROP TABLE IF EXISTS [FILE_SHARING_DB].[dbo].[FILES];
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [FILE_SHARING_DB].[dbo].[FILES]
(
    [ID]                   [int] IDENTITY (1,1) NOT NULL,
    [USERS_ID]			   [int]		        NOT NULL,
    [FILENAME]             [varchar](200)       NOT NULL,
    [MD5]                  [varchar](1500)      NOT NULL,
    [CREATED_AT]           [datetime]           NOT NULL,
    [MODIFIED_AT]          [datetime]           NOT NULL,
    CONSTRAINT [PK_FILES] PRIMARY KEY CLUSTERED
        (
         [ID] ASC
        ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
GO

ALTER TABLE [FILE_SHARING_DB].[dbo].[FILES]
    ADD DEFAULT (getdate()) FOR [CREATED_AT]
GO

ALTER TABLE [FILE_SHARING_DB].[dbo].[FILES]
    ADD DEFAULT (getdate()) FOR [MODIFIED_AT]
GO

ALTER TABLE [FILE_SHARING_DB].[dbo].[FILES]
	ADD CONSTRAINT FK_USERS_FILES
	FOREIGN KEY ([USERS_ID]) REFERENCES [FILE_SHARING_DB].[dbo].[USERS]([ID]);

GO

CREATE NONCLUSTERED INDEX [NonClusteredIndex-FILES.FILENAME] ON [FILE_SHARING_DB].[dbo].[FILES]
    (
     [FILENAME] ASC
    ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [NonClusteredIndex-FILES.MD5] ON [FILE_SHARING_DB].[dbo].[FILES]
    (
     [MD5] ASC
    ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
